- hosts: localhost
  become: true
  tasks:
    - name: Install packages
      state: present
      package: 
        - htop
        - neovim
        - tmux
        - git
        - bat
        - vim
        - gnome-tweaks
        - i3
