- hosts: localhost
  connection: local
  become: true
  
  tasks:
  - name: Install packages
    package:
      state: present
      name:
      - htop
      - neovim
      - tmux
      - git
      - bat
      - vim
      - gnome-tweaks
      - i3
